### ISSUE TITLE
Service single - Commerical scaffolding: Incorrect link used for Contact us hyperlink.  It will lead to error page instead of Contact us page.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/SMS-Contracting#100]
![image](https://cloud.githubusercontent.com/assets/11186313/15640619/8266871a-266c-11e6-8e3a-7c7b7dd9aae6.png)
Applicable to Services page:
![image](https://cloud.githubusercontent.com/assets/11186313/15643040/a9b105b4-267d-11e6-922f-e9d6645e0637.png)

**Comment by ganesh-titan** [comment]
FYI : I didn't uploded content.
Updated
