### ISSUE TITLE
Product listing: "View Detals" button label is supposed to have a font size of 14px. 

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/SMS-Contracting#118]
![image](https://cloud.githubusercontent.com/assets/11186313/15645700/9e297c58-268c-11e6-848a-deacb9cd8366.png)

**Comment by roseliesromeo** [comment]
Where in admin is the acf for the text label for the View Details button located?

**Comment by ganesh-titan** [comment]
Updated.
