### ISSUE TITLE
Gallery page: Where did you find 'Gallery' page, It's not mentioned in scope & Brief doc If needed style properly

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/SMS-Contracting#41]
![2016-05-02_1206](https://cloud.githubusercontent.com/assets/13309730/14975155/9a01cbb0-111c-11e6-9c21-9c832423c268.png)
![2016-05-02_1206_001](https://cloud.githubusercontent.com/assets/13309730/14975157/9c653d42-111c-11e6-8c54-3b4313770ec4.png)

**Comment by mahender-sowedane** [comment]
Equal space should be maintained.
![2016-05-12_1616](https://cloud.githubusercontent.com/assets/13309730/15212226/338eb436-185d-11e6-871a-bd1f26414970.png)

**Comment by mahender-sowedane** [comment]
Still issue is not fixed.

**Comment by ganesh-titan** [comment]
Hi,
This is unnecessary page. so removed.

Thank you.
