### ISSUE TITLE
Banner: Base of the description is cut.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/SMS-Contracting#52]
![image](https://cloud.githubusercontent.com/assets/11186313/15596112/4012aabe-23f7-11e6-895a-f42ed46fca37.png)

**Comment by roseliesromeo** [comment]
Not fixed, and it is even very obvious in firefox browser.
![image](https://cloud.githubusercontent.com/assets/11186313/15958396/faa23f8a-2f27-11e6-8174-f846407112ce.png)

**Comment by ganesh-titan** [comment]
@roseliesromeo : Will you please check again with hard refresh/clear cookies .
Thank you.

**Comment by roseliesromeo** [comment]
Issue reproduce by 2 users but looks good in 4 out of 6 users.
