### ISSUE TITLE
General: Page/section doesn't follow proper bootstrap grid.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/SMS-Contracting#85]
Header section:
![image](https://cloud.githubusercontent.com/assets/11186313/15604642/0d8ad9d0-2434-11e6-9277-96d2e5a83536.png)
Product listing:
![image](https://cloud.githubusercontent.com/assets/11186313/15605108/6e2faad4-2436-11e6-85da-af5116f4a70c.png)
Services page:
![image](https://cloud.githubusercontent.com/assets/11186313/15605193/0037a378-2437-11e6-88b1-5f2b4fbfb40b.png)
FAQ page:
![image](https://cloud.githubusercontent.com/assets/11186313/15605215/2a7cf9f8-2437-11e6-80ed-7ea75d047709.png)
Latest News:
![image](https://cloud.githubusercontent.com/assets/11186313/15605277/826cf280-2437-11e6-8bde-ae66b15a3343.png)

**Comment by ganesh-titan** [comment]
Hi @roseliesromeo : As per designs we are implemented. 
for example see screen shots belolw
![grid_issues](https://cloud.githubusercontent.com/assets/13450883/15820904/0d26a9aa-2c0a-11e6-9368-96de2749927b.jpg)
![Uploading issue_grid.jpg…]()
